### ISSUE TITLE
Stream ends after approx. 1h

### ISSUE THREAD

**Issue by timonmasberg** [aisstream/issues#17] opened 2023-05-11 18:38 UTC
First, let me thank you for the service. In our application, we experience that the stream stops sending messages after approximately 1h. Is there a reason for it? I do not see any documented time limit. There is no error thrown or any connection closing.

Thanks in advance!

**Comment by aisstream** [comment] 2023-05-11 23:44
This sounds like an issue on our end. Could you provide a sample of the client you are using to connect to aisstream.io as well the github account which created the API keys you are using ? 

If you do not feel comfortable here sharing the github account or a code sample you can email us the information at contact (at) aisstream.io referencing this issue in the title.

**Comment by aisstream** [comment] 2023-05-11 23:44
Could you also provide the bounding box you are using ?

**Comment by timonmasberg** [comment] 2023-05-12 08:50
I have created a gist with our code:

https://gist.github.com/timonmasberg/32b3dbbcb51d03ba527b3205a5d5c458

this is how we use it:
```
const aisClient: AISClient = new AISStreamioClient(
   "api key",
    [[
        // hamburg
        [53.3563, 9.5226],
        [53.6742, 10.2333],
    ]],
);

aisClient.stream$.subscribe() 
```

It logs incoming messages for up to an hour, and then we receive no further messages. The GitHub account is the current account I am writing from (timonmasberg)

**Comment by aisstream** [comment] 2023-05-12 15:47
Great, we will begin to look into why this is happening.

**Comment by aisstream** [comment] 2023-05-17 06:40
Just an update that we are looking into this and we haven't forgotten about the issue. W aim to ideally have an update in the coming days to why this is happening.

**Comment by aisstream** [comment] 2023-05-19 03:54
We have enabled per-client monitoring and some additional logging to try and get to the root cause of this issue. Could you confirm if this issue is still on-going for you ? 

We attempted to get your Gist running to test it but ran into some issues likely due to our inexperience with ts, would it be possible for you to provide a complete running index.js using the client ?

**Comment by timonmasberg** [comment] 2023-05-19 11:15
For now, I cannot verify this issue anymore. I started a stream on Postman and via the script and both running for 2h. This is weird, since you did not change anything on your side? We will keep checking if this issue will still exist in the following days. If not, I will close this issue.

**Comment by aisstream** [comment] 2023-05-23 02:35
Any objection to closing this ? I have observed our metrics and it appears you have been receiving data for greater than 18 hours without it dropping ?

**Closed as completed** 2023-05-23 06:15 UTC
